### ISSUE TITLE
[TODO] Janv/Fev 2019

### ISSUE THREAD

**Issue by A-312** [A-312/zds-site#10]
*Vous pouvez bien sûr m'aider à faire une de ces tâches ou faire intégralement cette issue. Ceci est juste un pense-bête, je ne réserve pas l'issue ou la PR. **Sauf mention contraire** dans l'issue.*

D'après : https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+involves%3AA-312+archived%3Afalse+sort%3Aupdated-desc+repo%3Azestedesavoir%2Fzds-site+

# TODO : 

 - [x] Icone des billets sur la page d'accueil https://github.com/zestedesavoir/zds-site/issues/4324
 - [x] Rajout de l'avatar dans le responsive design https://github.com/zestedesavoir/zds-site/issues/4615
 - [ ] Erreur sans design https://github.com/zestedesavoir/zds-site/issues/2165
 - [x] Clemoji v3 https://github.com/zestedesavoir/zds-site/issues/5069
 - [ ] Amélioration des notes avec du JS https://github.com/zestedesavoir/zds-site/issues/5113
 - [x] Activer l'environnement automatiquement : https://github.com/zestedesavoir/zds-site/issues/5163

# Non déterminé : 
 - [ ] https://github.com/A-312/zds-editor --> image en svg
 - [x] Cropper une image https://github.com/zestedesavoir/zds-site/issues/5190
