### ISSUE TITLE
[TODO] Amélioration profil/tribune

### ISSUE THREAD

**Issue by A-312** [A-312/zds-site#11]
*Vous pouvez bien sûr m'aider à faire une de ces tâches ou faire intégralement cette issue. Ceci est juste un pense-bête, je ne réserve pas l'issue ou la PR.*

# TODO
 - [x] QA et attendre : https://github.com/zestedesavoir/zds-site/pull/5025
 - [x] PR les corrections : 
         - 1ère liste : https://github.com/zestedesavoir/zds-site/pull/5025#issuecomment-418318329
         - 2ème liste : https://github.com/zestedesavoir/zds-site/pull/5025#issuecomment-458935836
 - [ ] Améliorer la recherche pour la page profil
 - [ ] Ajouter un breadcrumb pour les tutos + page profil : https://github.com/zestedesavoir/zds-site/issues/5090
 - [ ] Ajouter l'header pour les billets : https://github.com/zestedesavoir/zds-site/issues/5094
 - [ ] Considérer "Article de ...", "Tutoriel de ..." comme une sous page du profil : https://github.com/zestedesavoir/zds-site/issues/5091

**Comment by A-312** [comment]
@pierre-24 Pour le premier trimestre 2019 tu aurais le temps de mettre en place la recherche avec un pseudo ?

**Comment by pierre-24** [comment]
probablement pas :/

**Comment by A-312** [comment]
Tu sais s'il y a des exemples similaire à ce qu'on a sur Zeste de Savoir ?
