### ISSUE TITLE
[TODO] 1ère partie mi-2019

### ISSUE THREAD

**Issue by A-312** [A-312/zds-site#13]
- [ ] Tags automatiques quand du code est inclus : https://github.com/zestedesavoir/zds-site/issues/2344
 - [ ] Navigation au clavier : https://github.com/zestedesavoir/zds-site/issues/1194 ---> Correspond aussi à l'accessibilité du site.
 - [ ] Améliorer le sommaire/liste des catégories dans la sidebar : https://github.com/zestedesavoir/zds-site/issues/4396
 - [ ] Flux RSS : https://github.com/zestedesavoir/zds-site/issues/1194

**Comment by A-312** [comment]
- [ ] Éditeur Zds : https://github.com/A-312/zds-editor/
