### ISSUE TITLE
[TODO] Evolution de Gulp

### ISSUE THREAD

**Issue by A-312** [A-312/zds-site#7]
*Vous pouvez bien sûr m'aider à faire une de ces tâches ou faire intégralement cette issue. Ceci est juste un pense-bête, je ne réserve pas l'issue ou la PR.*

# TODO
- [x] Attendre : https://github.com/zestedesavoir/zds-site/pull/5172
- [x] Puis mettre à jour GULP. https://github.com/zestedesavoir/zds-site/issues/5213

# Optionnel

- [x] Optionnel mais indispensable : https://github.com/zestedesavoir/zds-site/issues/796
