### ISSUE TITLE
[TODO] Script d'installation & Travis ci

### ISSUE THREAD

**Issue by A-312** [A-312/zds-site#8]
*Vous pouvez bien sûr m'aider à faire une de ces tâches ou faire intégralement cette issue. Ceci est juste un pense-bête, je ne réserve pas l'issue ou la PR.*

# TODO : 

 - [x] Attendre : https://github.com/zestedesavoir/zds-site/pull/5188
 - [x] 2ème étape : Tester le script sur plusieurs machines https://github.com/zestedesavoir/zds-site/pull/5128

# Optionnel : 

 - [x] (Avant la 2ème étape), faire en sorte que travis utilise le même script d'installation que nous. Ref : https://github.com/zestedesavoir/zds-site/issues/5143#issuecomment-447053353
    - [x] Ajouter les dépendances manquantes : https://github.com/zestedesavoir/zds-site/issues/5144

# Objectif : 

 - Proposer le choix entre plusieurs OS à l'installation. Voir : https://github.com/zestedesavoir/zds-site/pull/5128#issuecomment-448725375

**Comment by A-312** [comment]
Essayez de reproduire : https://zestedesavoir.com/forums/sujet/11726/bug-de-ma-dev-zone/

**Comment by A-312** [comment]
Ajouter `●`  ça fait joli :D

**Comment by A-312** [comment]
(Bientôt corrigé via : #5299
