### ISSUE TITLE
[TODO] Drag'n'drop

### ISSUE THREAD

**Issue by A-312** [A-312/zds-site#9]
*Vous pouvez bien sûr m'aider à faire une de ces tâches ou faire intégralement cette issue. Ceci est juste un pense-bête, je ne réserve pas l'issue ou la PR.*

# TODO
 - [x] Attendre : https://github.com/zestedesavoir/zds-site/pull/5181
 - [x] zestedesavoir/zds-site/issues/5234 : Scroller à l'erreur
 - [ ] zestedesavoir/zds-site/issues/5231 : Emplacement du curseur : Utiliser ma lib [jquery.caret.js](https://github.com/A-312/jquery.caret.js) ?
 - [ ] zestedesavoir/zds-site/issues/5232 : Progressbar
 - [ ] zestedesavoir/zds-site/issues/4358 : Ajout d'un bouton notamment pour mobile (comme github ?)

# Commentaires : 
La zestedesavoir#5234 pourrait être fait en même temps que la zestedesavoir#5181
